version: '3.8'

services:
  # PostgreSQL数据库服务（开发环境）
  postgres-dev:
    image: postgres:15-alpine
    container_name: saber_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saber_game
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - saber_dev_network

  # Redis缓存服务（开发环境）
  redis-dev:
    image: redis:7-alpine
    container_name: saber_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - saber_dev_network

# 网络配置
networks:
  saber_dev_network:
    driver: bridge

# 数据卷配置
volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local